name: CI

on: push

jobs:
  build:
    name: Build, Test and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
        
      - name: Build project
        run: npm run build
        
      - name: Run Semantic Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
